# Generated by Django 2.0.3 on 2018-05-06 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('greyamp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='greyampdata',
            name='assginment',
        ),
        migrations.AddField(
            model_name='greyampdata',
            name='test',
            field=models.CharField(default='', max_length=6),
        ),
    ]
